
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.grammar;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int MAQ = 29;
  public static final int Y = 25;
  public static final int MULT = 22;
  public static final int CONST = 11;
  public static final int MAI = 31;
  public static final int IGUALNT = 28;
  public static final int IMPRIMIR = 15;
  public static final int ENTERO = 9;
  public static final int SI = 2;
  public static final int FUNCION = 12;
  public static final int O = 26;
  public static final int RESTA = 21;
  public static final int CORCHETE_C = 39;
  public static final int CORCHETE_A = 38;
  public static final int LLAVE_C = 37;
  public static final int LLAVE_A = 36;
  public static final int LEERENT = 16;
  public static final int PRINCIPAL = 19;
  public static final int IGUAL = 27;
  public static final int CARACTER = 47;
  public static final int SINO = 3;
  public static final int DEVUELVE = 13;
  public static final int MIENTRAS = 6;
  public static final int DIV = 23;
  public static final int CONTINUAR = 14;
  public static final int SUMA = 20;
  public static final int ID = 45;
  public static final int EOF = 0;
  public static final int ASIG = 33;
  public static final int COMILLAS = 41;
  public static final int error = 1;
  public static final int DIGITO = 44;
  public static final int COMA = 40;
  public static final int PAR_C = 35;
  public static final int MOD = 24;
  public static final int PAR_A = 34;
  public static final int LEERBOOL = 18;
  public static final int ROMPER = 8;
  public static final int MEQ = 30;
  public static final int VAL_BOL = 46;
  public static final int VACIO = 43;
  public static final int LEERCAR = 17;
  public static final int MEI = 32;
  public static final int P_COMA = 42;
  public static final int HACER = 7;
  public static final int BOOLEANO = 10;
  public static final int PARA = 5;
  public static final int SINOSI = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SI",
  "SINO",
  "SINOSI",
  "PARA",
  "MIENTRAS",
  "HACER",
  "ROMPER",
  "ENTERO",
  "BOOLEANO",
  "CONST",
  "FUNCION",
  "DEVUELVE",
  "CONTINUAR",
  "IMPRIMIR",
  "LEERENT",
  "LEERCAR",
  "LEERBOOL",
  "PRINCIPAL",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MOD",
  "Y",
  "O",
  "IGUAL",
  "IGUALNT",
  "MAQ",
  "MEQ",
  "MAI",
  "MEI",
  "ASIG",
  "PAR_A",
  "PAR_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMA",
  "COMILLAS",
  "P_COMA",
  "VACIO",
  "DIGITO",
  "ID",
  "VAL_BOL",
  "CARACTER"
  };
}

